#postgres DB
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/recipie_management_system?currentSchema=recipe_management_system
    username: shahawar
    password: random
  jpa:
    hibernate:
      ddl-auto: update
    spring.datasource.schema: recipe_management_system
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

#H2 DB
#spring:
#  datasource:
#    url: jdbc:h2:mem:recipe_management_system;INIT=CREATE SCHEMA IF NOT EXISTS recipe_management_system
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: password
#  mvc:
#    pathmatch:
#      matching-strategy: ANT_PATH_MATCHER
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#    show-sql: true
